version: '3.9'
services:
  base: &base
    image: brainstation/awscli:latest-ubuntu
    working_dir: /opt/code
    volumes:
      - ../:/opt/code
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN

  package:
    <<: *base
    command: bash -c -e "aws cloudformation package
      --template-file aws/cloudformation.yml
      --s3-bucket $BucketName
      --s3-prefix sam
      --output-template-file aws/cloudformation-package.yml
      --force-upload"

  deploy:
    <<: *base
    command: bash -c -e "aws cloudformation deploy
      --stack-name $StackName
      --template-file aws/cloudformation-package.yml
      --capabilities CAPABILITY_NAMED_IAM
      --no-fail-on-empty-changeset
      --parameter-overrides
      DataStreamName=$DataStreamName
      BucketName=$BucketName"
